
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label lblnum1;
	private global::Gtk.Entry txtnum2;
	private global::Gtk.Entry txtnum1;
	private global::Gtk.Label lblnum2;
	private global::Gtk.Label lblresul;
	private global::Gtk.Entry txtresul;
	private global::Gtk.Button btnsumar;
	private global::Gtk.Button btnrest;
	private global::Gtk.Button btnmult;
	private global::Gtk.Button btndvd;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblnum1 = new global::Gtk.Label ();
		this.lblnum1.Name = "lblnum1";
		this.lblnum1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.fixed1.Add (this.lblnum1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblnum1]));
		w1.X = 32;
		w1.Y = 26;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtnum2 = new global::Gtk.Entry ();
		this.txtnum2.CanFocus = true;
		this.txtnum2.Name = "txtnum2";
		this.txtnum2.IsEditable = true;
		this.txtnum2.InvisibleChar = '●';
		this.fixed1.Add (this.txtnum2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtnum2]));
		w2.X = 183;
		w2.Y = 69;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtnum1 = new global::Gtk.Entry ();
		this.txtnum1.CanFocus = true;
		this.txtnum1.Name = "txtnum1";
		this.txtnum1.IsEditable = true;
		this.txtnum1.InvisibleChar = '●';
		this.fixed1.Add (this.txtnum1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtnum1]));
		w3.X = 183;
		w3.Y = 24;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblnum2 = new global::Gtk.Label ();
		this.lblnum2.Name = "lblnum2";
		this.lblnum2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2");
		this.fixed1.Add (this.lblnum2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblnum2]));
		w4.X = 33;
		w4.Y = 66;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblresul = new global::Gtk.Label ();
		this.lblresul.Name = "lblresul";
		this.lblresul.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.lblresul);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblresul]));
		w5.X = 31;
		w5.Y = 119;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtresul = new global::Gtk.Entry ();
		this.txtresul.CanFocus = true;
		this.txtresul.Name = "txtresul";
		this.txtresul.IsEditable = true;
		this.txtresul.InvisibleChar = '●';
		this.fixed1.Add (this.txtresul);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtresul]));
		w6.X = 184;
		w6.Y = 114;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnsumar = new global::Gtk.Button ();
		this.btnsumar.CanFocus = true;
		this.btnsumar.Name = "btnsumar";
		this.btnsumar.UseUnderline = true;
		this.btnsumar.Label = global::Mono.Unix.Catalog.GetString ("Sumar");
		this.fixed1.Add (this.btnsumar);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnsumar]));
		w7.X = 35;
		w7.Y = 186;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnrest = new global::Gtk.Button ();
		this.btnrest.CanFocus = true;
		this.btnrest.Name = "btnrest";
		this.btnrest.UseUnderline = true;
		this.btnrest.Label = global::Mono.Unix.Catalog.GetString ("Restar");
		this.fixed1.Add (this.btnrest);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnrest]));
		w8.X = 112;
		w8.Y = 186;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnmult = new global::Gtk.Button ();
		this.btnmult.CanFocus = true;
		this.btnmult.Name = "btnmult";
		this.btnmult.UseUnderline = true;
		this.btnmult.Label = global::Mono.Unix.Catalog.GetString ("Multiplicar");
		this.fixed1.Add (this.btnmult);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnmult]));
		w9.X = 198;
		w9.Y = 186;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btndvd = new global::Gtk.Button ();
		this.btndvd.CanFocus = true;
		this.btndvd.Name = "btndvd";
		this.btndvd.UseUnderline = true;
		this.btndvd.Label = global::Mono.Unix.Catalog.GetString ("Dividir");
		this.fixed1.Add (this.btndvd);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btndvd]));
		w10.X = 300;
		w10.Y = 186;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnsumar.Clicked += new global::System.EventHandler (this.OnBtnsumarClicked);
		this.btnrest.Clicked += new global::System.EventHandler (this.OnBtnrestClicked);
		this.btnmult.Clicked += new global::System.EventHandler (this.OnBtnmultClicked);
		this.btndvd.Clicked += new global::System.EventHandler (this.OnBtndvdClicked);
	}
}
